project:
  type: website
  output-dir: docs
website:
  title: "Justin Dollman"
  navbar:
    right:
      - about.qmd
      - teaching.qmd

format:
  html:
    theme:
      light: zephyr
      dark: quartz
    css: styles.css

editor: source

