project:
  type: website
  output-dir: docs
website:
  title: ""
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - math-camp-homepage.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: source

