project:
  type: website
  output-dir: docs
website:
  title: "Justin Dollman"
  navbar:
    right:
      - about.qmd
      - posts.qmd
format:
  html:
    theme: zephyr
    css: styles.css

editor: source

