---
title: "Chapter 2: Vectors, what even are they?"
format: html
---

# 

The three perspectives on what we mean by "vector"

Let's ignore the mathematician's perspective

An arrow inside a coordinate system

tail on the origin -- that's unlike the physics perspective

This is something hinted at in the video. How would you go from the vector-as-arrow perspective to the vector-as-list-of-numbers perspective?

The arrow's "tip" lies at a certain coordinate in $n$-space. That **coordinate** can be represented as a list of numbers.

What's the difference between $\begin{pmatrix} 6 & 9 \end{pmatrix}$ and $\begin{bmatrix} 6 \\ 9 \end{bmatrix}$?
The former is a *point* and the latter is a *vector*.

Vector addition.

The diagonal of the parallelogram (he doesn't cover that -- but you should)

Vector multiplication (scalar-vector multiplication)

k > 1, 0 < k < 1
Scaling a vector, scalar

GS says that, in LA, numbers go around scaling so much that it's commong to use "number" and "scalar" interchangeably. Just to be clear, though the contents ... maybe ... IDK.

I don't think he mentions anything about vector notation!

What does it mean for vectors to be linearly dependent?

These are possibly from another video:
What does it mean to think of each element of a vector as a scalar?
Answer: Entry $v_i$ scales the corresponding $\hat e_i$ (superior notation to i, j, k -- reminds me of how Laura bragged about Bogota street names)
? Something about each vector is a recipe for scaling and adding together unit vectors
I think he must mean $\vec v = \sum_{i = 1}^n v_i \hat e_i$


How does GS explain the meaning of "basis" in "basis vectors"?

Show how, for any target vector $\vec v = \begin{pmatrix} v_1 \\ v_2 \end{pmatrix}$, you can get there using any two linearly independent vectors.
And then you can think of those combinations you generate as being the coordinates of that vector were those the two basis vectors spanning the space
(it's easy to see when the unit vectors are those ones you're using)

What's a linear combination and whence the "linear" in "linear combination"?

What's the span of a single vector?
$\vec v = \begin{bmatrix} v \end{bmatrix}$
$\vec v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$
$\vec v = \begin{bmatrix} v_1 \\ v_2 \\ v_3\end{bmatrix}$
(can't visualize past that!)

What's the span of two vectors?

