---
title: "Chapter 5: Matrix multiplication"
format: html
---

Linear transformations are functions with vectors as inputs and vectors as outputs

For previous video
Why is it the case that (or what is meant by) any linear transformation can be completely described by what it does to the basis vectors?
Answer: If the original vector is $$\vec w = \begin{bmatrix} w_1 \\ w_2 \end{bmatrix}$$, then its coordinates after the transformation will be $$\begin{bmatrix} w_1 L(\hat i) \\ w_2 L(\hat j) \end{bmatrix}$$

A composition is when you apply multiple transformations

What's the 'geometric meaning' of multiplying matrices?
First multiplying by one, then multiplying by the other.

Reading right to left (and multiplication not being commutative)

This one's laborious. What's the Grant Sanderson way of notating out matrix multiplication? Use these two matrices (which, to make things spicy, contain the first eight letters of the Greek alphabet)

$$\begin{bmatrix} \alpha & \beta \\ \gamma &  \delta  \end{bmatrix} \cdot \begin{bmatrix} \epsilon & \zeta \\ \eta &  \theta \end{bmatrix}$$
Answer

$$\begin{bmatrix} \alpha & \beta \\ \gamma &  \delta  \end{bmatrix} \cdot \begin{bmatrix} \epsilon & \zeta \\ \eta &  \theta \end{bmatrix} = \left [  \epsilon \begin{bmatrix} \alpha \\ \gamma \end{bmatrix} + \eta \begin{bmatrix} \beta \\ \delta \end{bmatrix} \ \ \ \zeta \begin{bmatrix} \alpha \\ \gamma \end{bmatrix} + \theta \begin{bmatrix} \beta \\ \delta \end{bmatrix}\right ]$$
What should we take from this?
Make sure you've done the problems! https://www.3blue1brown.com/lessons/matrix-multiplication