---
title: "Chapter 7: The determinant"
format: html
---

What's GS's successive argumentation to show that the change in area for *any* shape will be scaled by the same amount?

A: Unit square. Then, what happens to one square happens any square, because of the parallel and evenly spaced gridlines theorem. From that it follows then any shape (which can be approximated as a bunch of squares) will suffer the same multiplication by a factor

What has determinants?
Transformations (matrix)

What does a determinant of zero mean?
If the transformation reduces the dimensionality of space.

Negative determinants

'invert the orientation of space'
Normally you'd have j hat to the left of i hat. If that changes, you've reversed the orientation of space. But what does that ... mean. How could you operationalize this?

Ask what the x-axis is in the screenshot of Det I took.

Parallelepiped

Right-hand rule and left-hand rule

Intuition.

$ad - 0 \cdot 0$
And these generate paralellograms with height d and base a
$ad - b \cdot 0$
$ad - 0 \cdot d$

