---
title: "Chapter 3: Linear combinations, span, and basis vectors"
format: html
---

https://www.youtube.com/watch?v=k7RM-ot2NWY

```{r}
flecha <- function(xend, yend) {
  geom_segment(aes(
    x = 0,
    y = 0,
    xend = xend,
    yend = yend
  ),
  arrow = arrow(
    angle = 20,
    length = unit(0.1, 'inches'),
    type = 'closed'
  ))
}

punto <- function(x, y){
  geom_point(
    data = data.frame(x = x, y = y),
    aes(x, y))
}
```


What is a linear combination of vectors?

What's the span of a set of vectors?

Staying on the 2D plane, 

linear combinations of two vectors can have different *span* different 
A: (Don't know the question). If the two vectors are linearly independent, they will span the entire 2D plane. If they are on the same line, they will only span that line. If they are both the zero vector, they span ... the origin.

If two vectors $\vec v, \vec w \in \mathbb R^2$ are linearly dependent, how would indicate that given the following template $\_\vec v = \_ \vec w$, where the $\_$ is a 'blank' to be filled in.
It's a bit tricky because you actually only *need* to fill in one blank, $\vec v = a \vec w$, where $a$ is the scalar that *scales* $\vec w$ to equal $\vec v$.

What if we add a third vector? How would that change the situation?

How do you write a linear combination of three vectors?
$a\vec v + b\vec w + c\vec u$

Now, how many elements would those vectors $\vec v, \vec w, \vec u$ have?
A bit of a trick question!

Ok, this wasn't covered in the video, but how would you write a linear combination of 28 vectors? Hint: You'll use a certain tool...

$$\sum_{i=1}^{28} a_i\vec v_i,\ i = 1, \ldots, 28$$, where $a_i$ are your 28 scalars multiplying your 28 vectors, $\vec v_i$. 28 is just a random number; hopefully you see that the idea is that now you have a way to write a combination of an arbitrary number of vectors, $$\sum_{i=1}^{n} a_i\vec v_i,\ i = 1, \ldots, n$$
Final question

"Given how I described a basis and given the meanings of span and linearly independent, why is the technical definition of basis the right one?"

Here's the technical definition, "The basis of a vector space is a set of linearly independent vectors that span the full space"