---
title: "Chapter 11: Cross Products"
format: html
---

The initial image for this chapter is a parallelogram that two vectors create (by copying them)

v \times w is the area of the parallelogram

It can be negative (which means that order matters)

What Sanderson's mnemonic for the sign of the cross-product?
(See screenshot)
He uses the fact that i \times j is +1, so if v \times w also has v to w's right, then it's positive as well (by analogy)
And this is because v represents where i hat lands (remember, if i hat and j hat flip, then the orientation flipped and so the area is negative)

How is the determinant relevant to the cross-product?
You put the two vectors as columns in a matrix and then compute the determinant (... but what if you had two three dimensional vectors??)

More perpendicular, bigger parallelogram

av \times w = a(v \times w)

How does new vector's length related to the parallelogram created by two vectors?

a) equal to the *area* of the parallelogram created by two 3D vectors
b) perpendicular to the parallelogram
(note that these two facts don't uniquely determine the direction of the cross-product -- use the right-hand rule for that)

Sanderson mentions the 'trick' we can use to calculate the cross-product

$$\text{det}\begin{pmatrix} \hat i & u_1 & v_1 \\ \hat j & u_2 & v_2 \\ \hat k & u_3 & v_3  \end{pmatrix}$$

What would happen if instead we calculated the following:

$$\text{det}\begin{pmatrix} \hat i & \hat j & \hat k \\ u_1 & u_2 & u_3 \\ v_1 & v_2 & v_3  \end{pmatrix}$$

Nothing would change! It's an equally valid way to calculate the cross product. The reason $\text{det} (\textbf A) = \text{det} (\textbf A^T)$

Given two vector lengths (as in, imagine you have arrows of a given size, but you can point them wherever you want), how can you maximize the parallelogram they create?

$$0 = \frac d{d\theta} (|a||b|\sin \theta) = |a||b|\cos \theta$$ Now, to get $|a||b|\cos \theta = 0$, $\cos \theta$ has to be zero, and this happens at $\pi$ and $\frac {3\pi} 2$