---
title: "Chapter 16: A quick trick for computing eigenvalues"
format: html
---

#

This was brought up at breakneck speed, but can you remember what a matrix's characteristic polynomial is?

How are eigenvalues related to a matrix's characteristic polynomial?
Eigenvalues are the roots of a matrix's characteristic polynomial.

What was the trace of a matrix?
If your matrix is $$\begin{bmatrix} a & b \\ c & d \end{bmatrix}$$, then it's $a + d$.

Ok, but most matrices are bigger than 2x2. How would you generalize the concept of a $\text{tr}(\textbf A)$?
The sum of $\text{diag}(\textbf A)$, or, $$\sum_{i=1}^n a_{ii}$$

How is a matrix's trace related to its eigenvalues? Note: there are two ways to answer, one is more straightforward, the other is more relevant to where we're going

$\text{tr}(\textbf A) = \sum_{i=1}^n \lambda_i$. You can divide both sides by $n$ to get $n^{-1}\text{tr}(\textbf A) = n^{-1}\sum_{i=1}^n \lambda_i = \text{mean}(\lambda_i)$

In the $\textbf A \in \mathbb R^2$ case, we have $a + d = \lambda_1 + \lambda_2$ or $\frac{a + d}2 = \frac{\lambda_1 + \lambda_2}2$

Enough trace for now. How is the *determinant* of a matrix related to its eigenvalues?

$$\text{det}(\textbf A) = \Pi_{i=1}^n \lambda_i$$

In the $\textbf A \in \mathbb R^2$ case, we have $ad - bc = \lambda_1 \lambda_2$

I need to go back and find out how he got that the eigenvalues are evenly spaced from ... what?