---
title: "Chapter 12: The Other Way to Visualize Derivatives"
format: html
---

# for a previous video

The derivative of a function is a new function that for every input returns the slope at that point.

#

https://www.3blue1brown.com/lessons/derivatives-and-transforms

What does Grant call this generalized way of understanding derivatives?
"The transformational view"

In what way will it be more general?
It "generalize[s] calculus beyond functions whose inputs and output are simply numbers." That is, functions whose inputs and outputs are real numbers.

Can you complete this phrase from the video, *I'd encourage you not think of this derivative-as-slope idea as being the definition of the derivative; instead think of the derivative as ...* 
'... as asking how sensitive is the function to tiny nudges around a given input.' Interestingly he then goes on to show a picture of mapping numbers on a number line to their corresponding number on a different number line ... seems like reals to reals!

Q: In your own words, what's this 'stretch/squish' understanding of the derivative?
A: 'If you take a small area around a point on a number line $[x_0 -a, x_0 + a]$, the derivative of at that point is about how much those points are being stretched (if $|f'(x_0)| > 1$) or squished (if $|f'(x_0)| < 1$) on the 'output' number line. So, they become spread out if the function stretches inputs around $x_0$ and they become contracted if the derivative is 

Q: In this numberline-to-numberline 'transformational view' hat does it look like to have a derivative of zero?
A: It looks as if the points just stack atop each other.
Note: he does x^2, you should do x^3 + 3x (wait, how does that never have a derivative of zero?!)

What are the two kinds of fixed points? That is, what are their respective names and what defines them?
A: Stable and unstable fixed points.